# Define a JSON log format named "json_combined"
# Include this *inside* the "http" block of nginx.conf

    log_format json_combined escape=json
    '{'
      '"time":"$time_iso8601",'
      '"remote_addr":"$remote_addr",'
      '"x_forwarded_for":"$http_x_forwarded_for",'
      '"request_method":"$request_method",'
      '"request_uri":"$request_uri",'
      '"status":$status,'
      '"body_bytes_sent":$body_bytes_sent,'
      '"request_time":$request_time,'
      '"http_referer":"$http_referer",'
      '"http_user_agent":"$http_user_agent"'
    '}';


