# Define a JSON log format named "json_combined"
# Include this *inside* the "http" block of nginx.conf

# "time" or "timestamp"?  Not clear but "timestamp" seems to be more common.
# "request_method" and "request_uri" instead of just "request" - enables granular filtering
# "request_id" assigned by Nginx and used to trace requests & replies
# "level" (optional) not needed but consistent with other attributes from other logging components.
# "service" make it clear what component is emitted the log entry?

    log_format json_combined escape=json
    '{'
      '"timestamp":"$time_iso8601",'
      '"service":"nginx",'
      '"request_id":"$request_id",' 
      '"remote_addr":"$remote_addr",'
      '"x_forwarded_for":"$http_x_forwarded_for",'
      '"request_method":"$request_method",'
      '"request_uri":"$request_uri",'
      '"status":$status,'
      '"body_bytes_sent":$body_bytes_sent,'
      '"request_time":$request_time,'
      '"http_referer":"$http_referer",'
      '"http_user_agent":"$http_user_agent"'
    '}';
