# Define a "logfmt" logging format named "logfmt_combined"
# Include this *inside* the "http" block of nginx.conf

    log_format logfmt_combined
      'time=$time_iso8601 '
      'remote_addr=$remote_addr '
      'x_forwarded_for="$http_x_forwarded_for" '
      'method=$request_method '
      'uri="$request_uri" '
      'status=$status '
      'bytes=$body_bytes_sent '
      'request_time=$request_time '
      'referer="$http_referer" '
      'user_agent="$http_user_agent"';

