# version: '3.9'
services:
  todo:
    build: .
    container_name: todo
    # A volume mount-binds ./src (on host) to /app/ (in container).
    # This means that changes to code in "app" are immediately reflected in 
    # the running container.
    # Useful for development if 'CMD' includes the "--reload" option.
    # This avoids mounting other directories in the container,
    # such as backend/tests, backend/experiments.
    # For production, you should remove this.
    volumes:
      - ./data:/app/data
    # For production, do not expose port 8000. 
    # Instead, require clients to use nginx as proxy.
    ports:
      - "8000:8000"
    environment:
      # These values are defined in .env
      TODO_URL: ${TODO_URL}
      # Logging
      LOG_LEVEL: ${LOG_LEVEL}
    healthcheck:
      # Use urllib.request instead of curl. curl may not be installed in Docker image.
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - todo-net

  nginx:
    # Nginx web server as proxy. 
    # Listen on port 8080 on the native host, mapped to port 80 in container.
    # nginx:alpine is smaller than nginx:stable (52MB vs 199MB) and requires less memory.
    # nginx:alpine includes fewer nginx modules, fewer libraries, and musl libc instead of glibc.
    image: nginx:alpine
    container_name: nginx_todo_gateway
    ports:
      - "80:80"
      - "443:443" # Reserved for HTTPS, not yet configured in nginx.
    volumes:
      - ./nginx/conf:/etc/nginx:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - todo
    networks:
      - todo-net

  
networks:
  todo-net:
    driver: bridge

# Containers on the same network (todo-net) communicate using the
# *internal container ports* not the host-mapped ports.
# Hence, nginx-exporter scrapes nginx on port 80 instead of 8080.
# They also use internal DNS names, like 'nginx' or 'backend'.
